location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_llcp
    name: mrs_llcp
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_llcp
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_llcp
    name: mrs_llcp
    rev: 1df25938caa5d4b195fce8a8a8b9051841aa8c25
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_llcp
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
