location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_llcp
    name: mrs_llcp
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_llcp
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_llcp
    name: mrs_llcp
    rev: cc166180238f797c24c52f24f90897468fba8ccb
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_llcp
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
