location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_llcp
    name: mrs_llcp
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_llcp
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_llcp
    name: mrs_llcp
    rev: 66297525685544e4a339a75af2cc4654764f5663
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_llcp
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
